apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: lab-demo
spec:
  selector:
    app: joke-backend
  ports:
  - port: 5055
    targetPort: 5055
    nodePort: 32302
  type: NodePort
