apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: lab-demo
spec:
  selector:
    app: joke-frontend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 32301
  type: NodePort
